version: '3.8'
services:
  platform:
    build: .
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_KEY: ${STRIPE_WEBHOOK_KEY}
      DATABASE_URL: ${DATABASE_URL}
      PHYLLO_KEY: ${PHYLLO_KEY}
      NUXT_SESSION_PASSWORD: ${NUXT_SESSION_PASSWORD}

      NUXT_OIDC_TOKEN_KEY: ${NUXT_OIDC_TOKEN_KEY}
      NUXT_OIDC_SESSION_SECRET: ${NUXT_OIDC_SESSION_SECRET}
      NUXT_OIDC_AUTH_SESSION_SECRET: ${NUXT_OIDC_AUTH_SESSION_SECRET}
      NUXT_OIDC_PROVIDERS_AUTH0_BASE_URL: ${NUXT_OIDC_PROVIDERS_AUTH0_BASE_URL}
      NUXT_OIDC_PROVIDERS_AUTH0_CLIENT_ID: ${NUXT_OIDC_PROVIDERS_AUTH0_CLIENT_ID}
      NUXT_OIDC_PROVIDERS_AUTH0_CLIENT_SECRET: ${NUXT_OIDC_PROVIDERS_AUTH0_CLIENT_SECRET}
      NUXT_OIDC_PROVIDERS_AUTH0_REDIRECT_URI: ${NUXT_OIDC_PROVIDERS_AUTH0_REDIRECT_URI}
      NUXT_SUPABASE_SECRET: ${NUXT_SUPABASE_SECRET}

      NUXT_MAILER_DRIVER: ${NUXT_MAILER_DRIVER}
      NUXT_MAILER_HOST: ${NUXT_MAILER_HOST}
      NUXT_MAILER_PORT: ${NUXT_MAILER_PORT}
      NUXT_MAILER_USER: ${NUXT_MAILER_USER}
      NUXT_MAILER_PASS: ${NUXT_MAILER_PASS}

      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      BASE_URL: ${BASE_URL}
      CREATOR_API_KEY: ${CREATOR_API_KEY}

    ports:
      - "3000:3000"
    restart: unless-stopped